version: "3.8"

services:
  app:
    build:
      context: .
    environment:
      SUPABASE_USER: ${SUPABASE_USER}
      SUPABASE_PASSWORD: ${SUPABASE_PASSWORD}
      SUPABASE_HOST: ${SUPABASE_HOST}
      SUPABASE_PORT: ${SUPABASE_PORT}
      SUPABASE_DBNAME: ${SUPABASE_DBNAME}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8081:8081"
